In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def import_stats_file(filename):
    df = pd.read_csv(filename, sep=',', index_col='endDate')
    return df
    
df1 = import_stats_file('stats_type0_8_5.csv')  
df1.tail(10)


#plt(df1['mean'])

,patternID,actualReturn,mean,variance,median,upside,downside,#searchResults
endDate,,,,,,,,
2001-09-04,SP500,-0.083120,0.003127,0.000513,0.003064,0.025779,-0.018496,600
2005-05-12,SP500,0.027360,0.000007,0.000296,0.000726,0.016542,-0.018094,600
2010-06-11,SP500,0.023736,0.003349,0.000655,0.005227,0.026124,-0.024252,600
2006-06-13,SP500,0.013427,0.002261,0.000779,0.002935,0.026335,-0.020071,600
2011-02-07,SP500,0.010060,0.000554,0.000289,0.001191,0.014621,-0.014536,600
2002-07-08,SP500,-0.060441,0.001657,0.000416,0.003126,0.020535,-0.020193,600
2001-04-19,SP500,-0.015291,0.001599,0.000432,0.003393,0.020657,-0.019324,600
2002-05-22,SP500,-0.019668,0.000945,0.000376,0.001574,0.020298,-0.018285,600
2006-10-11,SP500,0.011741,0.000442,0.000230,0.002716,0.014134,-0.016699,600
2011-08-22,SP500,0.076756,0.003093,0.000709,0.002850,0.030312,-0.023003,600

In [27]:
df1.corr()

,actualReturn,mean,variance,median,upside,downside,#searchResults
actualReturn,1.000000,0.008399,0.064986,-0.001133,0.053654,-0.067988,NaN
mean,0.008399,1.000000,0.357979,0.711833,0.556350,-0.089651,NaN
variance,0.064986,0.357979,1.000000,0.309495,0.906643,-0.862352,NaN
median,-0.001133,0.711833,0.309495,1.000000,0.281074,-0.125362,NaN
upside,0.053654,0.556350,0.906643,0.281074,1.000000,-0.806794,NaN
downside,-0.067988,-0.089651,-0.862352,-0.125362,-0.806794,1.000000,NaN
#searchResults,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
import scipy.stats
scipy.stats.pearsonr(df1.mean, df1.actualReturn)

TypeError: len() of unsized object

actualReturn    1.000000
mean            0.008399
variance        0.064986
median         -0.001133
upside          0.053654
downside       -0.067988
dtype: float64

In [33]:
df1[df1.columns[1:-1]].apply(lambda x: x.corr(df1['actualReturn']))

actualReturn    1.000000
mean            0.008399
variance        0.064986
median         -0.001133
upside          0.053654
downside       -0.067988
dtype: float64